// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: first.proto

#ifndef PROTOBUF_first_2eproto__INCLUDED
#define PROTOBUF_first_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace tutorial {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_first_2eproto();
void protobuf_AssignDesc_first_2eproto();
void protobuf_ShutdownFile_first_2eproto();

class StringMsg;
class Int32Msg;

// ===================================================================

class StringMsg : public ::google::protobuf::Message {
 public:
  StringMsg();
  virtual ~StringMsg();

  StringMsg(const StringMsg& from);

  inline StringMsg& operator=(const StringMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StringMsg& default_instance();

  void Swap(StringMsg* other);

  // implements Message ----------------------------------------------

  StringMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StringMsg& from);
  void MergeFrom(const StringMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:tutorial.StringMsg)
 private:
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  friend void  protobuf_AddDesc_first_2eproto();
  friend void protobuf_AssignDesc_first_2eproto();
  friend void protobuf_ShutdownFile_first_2eproto();

  void InitAsDefaultInstance();
  static StringMsg* default_instance_;
};
// -------------------------------------------------------------------

class Int32Msg : public ::google::protobuf::Message {
 public:
  Int32Msg();
  virtual ~Int32Msg();

  Int32Msg(const Int32Msg& from);

  inline Int32Msg& operator=(const Int32Msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Int32Msg& default_instance();

  void Swap(Int32Msg* other);

  // implements Message ----------------------------------------------

  Int32Msg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Int32Msg& from);
  void MergeFrom(const Int32Msg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 val = 1;
  inline bool has_val() const;
  inline void clear_val();
  static const int kValFieldNumber = 1;
  inline ::google::protobuf::int32 val() const;
  inline void set_val(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tutorial.Int32Msg)
 private:
  inline void set_has_val();
  inline void clear_has_val();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 val_;
  friend void  protobuf_AddDesc_first_2eproto();
  friend void protobuf_AssignDesc_first_2eproto();
  friend void protobuf_ShutdownFile_first_2eproto();

  void InitAsDefaultInstance();
  static Int32Msg* default_instance_;
};
// ===================================================================


// ===================================================================

// StringMsg

// required string name = 1;
inline bool StringMsg::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StringMsg::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StringMsg::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StringMsg::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& StringMsg::name() const {
  // @@protoc_insertion_point(field_get:tutorial.StringMsg.name)
  return *name_;
}
inline void StringMsg::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:tutorial.StringMsg.name)
}
inline void StringMsg::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:tutorial.StringMsg.name)
}
inline void StringMsg::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tutorial.StringMsg.name)
}
inline ::std::string* StringMsg::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:tutorial.StringMsg.name)
  return name_;
}
inline ::std::string* StringMsg::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void StringMsg::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:tutorial.StringMsg.name)
}

// -------------------------------------------------------------------

// Int32Msg

// required int32 val = 1;
inline bool Int32Msg::has_val() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Int32Msg::set_has_val() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Int32Msg::clear_has_val() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Int32Msg::clear_val() {
  val_ = 0;
  clear_has_val();
}
inline ::google::protobuf::int32 Int32Msg::val() const {
  // @@protoc_insertion_point(field_get:tutorial.Int32Msg.val)
  return val_;
}
inline void Int32Msg::set_val(::google::protobuf::int32 value) {
  set_has_val();
  val_ = value;
  // @@protoc_insertion_point(field_set:tutorial.Int32Msg.val)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace tutorial

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_first_2eproto__INCLUDED
